/*
   File: tbl_parent.sql
   Author: David Válek
   Description: Table definition for Parent
   Created: 2025-08-15
*/
create table parent (
   parent_id  number
      generated by default as identity
   CONSTRAINT pk_parent PRIMARY KEY,
   person_id  number not null,
   constraint fk_parent_person foreign key ( person_id )
      references person ( person_id )
);