/*
   File: tbl_student.sql
   Author: David Válek
   Description: Table definition for Student, which stores information about students
   Created: 2025-08-15
   Modified: 2025-08-16 - Simplified to only contain student_id, person_id FK, and class_id
*/
create table student (
   student_id    number
      generated by default as identity
   primary key,
   person_id     number not null,
   class_id      number null,
   constraint fk_student_person foreign key ( person_id )
      references person ( person_id ),
   constraint fk_student_class foreign key ( class_id )
      references class ( class_id )
);