/*
   File: tbl_parent.sql
   Author: David Válek
   Description: Table definition for Parent
   Created: 2025-08-15
*/
create table parent (
   parent_id  number
      generated by default as identity
   primary key,
   first_name varchar2(50) not null,
   last_name  varchar2(50) not null,
   email      varchar2(100) not null unique,
   password   varchar2(256) default 'password' not null
);