/*
   File: tbl_grade_group.sql
   Author: David Válek
   Description: Table definition for Grade_Group, which stores information about the grade groups in the system.
                Grade groups are eg. tests, quizzes, etc.
   Created: 2025-08-15
*/
create table grade_group (
   grade_group_id number generated by default as identity primary key,
   subject_id number not null,
   teacher_id number not null,
   grade_group_date timestamp default current_timestamp not null,
   name varchar2(50) not null,
   description varchar2(255),
   constraint fk_grade_group_subject foreign key (subject_id) references subject(subject_id),
   constraint fk_grade_group_teacher foreign key (teacher_id) references teacher(teacher_id)
);