/*
   File: tbl_classroom.sql
   Author: David Válek
   Description: Table definition for Classroom, which is room where the lectures take place
   Created: 2025-08-15
*/
create table classroom (
   classroom_id number
      generated by default as identity
   primary key,
   name         varchar2(50) not null,
   capacity     number not null
);