/*
   File: tbl_grade.sql
   Author: David Válek
   Description: Table definition for Grade, which stores the grades given to students
   Created: 2025-08-15
*/
create table grade (
   grade_id   number
      generated by default as identity
   primary key,
   student_id number not null,
   subject_id number not null,
   teacher_id number not null,
   grade      number(1) not null check ( grade between 1 and 5 ),
   grade_date date default sysdate not null,
   constraint fk_grade_student foreign key ( student_id )
      references student ( student_id ),
   constraint fk_grade_subject foreign key ( subject_id )
      references subject ( subject_id ),
   constraint fk_grade_teacher foreign key ( teacher_id )
      references teacher ( teacher_id )
);