/*
   File: tbl_teacher.sql
   Author: David Válek
   Description: Table definition for Teacher, which stores information about teachers
   Created: 2025-08-15
*/
create table teacher (
   teacher_id number
      generated by default as identity
   primary key,
   first_name varchar2(50) not null,
   last_name  varchar2(50) not null,
   email      varchar2(100) not null unique
);