/*
   File: tbl_person.sql
   Author: David Válek
   Description: Table definition for Person
   Created: 2025-08-15
*/
create table person (
   person_id  number
      generated by default as identity
   CONSTRAINT pk_person PRIMARY KEY,
   first_name varchar2(50) not null,
   last_name  varchar2(50) not null,
   email      varchar2(100) not null,
   password_hash   varchar2(256) default 'password' not null,
   salt       varchar2(32) default 'salt' not null,
   constraint uq_person_email unique (email),
   constraint chk_email_format check (email like '%@%.%')

);