/*
   File: tbl_lecture.sql
   Author: David Válek
   Description: Table definition for Lecture, which stores information about lectures
   Created: 2025-08-15
*/
create table lecture (
   lecture_id   number
      generated by default as identity
   CONSTRAINT pk_lecture PRIMARY KEY,
   subject_id   number not null,
   classroom_id number not null,
   start_time   timestamp not null,
   end_time     timestamp not null,
   lecture_name varchar2(100) default null,
   description  varchar2(500) default null,
   constraint uq_lecture_subject_id_classroom_id_start_time unique (subject_id, classroom_id, start_time),
   constraint fk_lecture_subject foreign key ( subject_id )
      references subject ( subject_id ),
   constraint fk_lecture_classroom foreign key ( classroom_id )
      references classroom ( classroom_id )
);