/*
   File: tbl_lecture.sql
   Author: David Válek
   Description: Table definition for Lecture, which stores information about lectures
   Created: 2025-08-15
*/
create table lecture (
   lecture_id   number
      generated by default as identity
   primary key,
   subject_id   number not null,
   teacher_id   number not null,
   classroom_id number not null,
   start_time   timestamp not null,
   end_time     timestamp not null,
   constraint fk_lecture_subject foreign key ( subject_id )
      references subject ( subject_id ),
   constraint fk_lecture_teacher foreign key ( teacher_id )
      references teacher ( teacher_id ),
   constraint fk_lecture_classroom foreign key ( classroom_id )
      references classroom ( classroom_id )
);