/*
   File: tbl_teacher.sql
   Author: David Válek
   Description: Table definition for Teacher, which stores information about teachers
   Created: 2025-08-15
*/
create table teacher (
   teacher_id number
      generated by default as identity
   CONSTRAINT pk_teacher PRIMARY KEY,
   person_id  number not null,
   constraint fk_teacher_person foreign key ( person_id )
      references person ( person_id )
);