/*
   File: tbl_class_group.sql
   Author: David Válek
   Description: Table definition for Class_Group, which links classes to their groups
   Created: 2025-08-19
*/
create table class_group (
   class_group_id number
      generated by default as identity
   primary key,
   class_id       number not null,
   group_name     varchar2(100),
   constraint fk_class_group_class foreign key ( class_id )
      references class ( class_id )
);