/*
   File: tbl_student.sql
   Author: David Válek
   Description: Table definition for Student, which stores information about students
   Created: 2025-08-15
*/
create table student (
   student_id    number
      generated by default as identity
   primary key,
   first_name    varchar2(50) not null,
   last_name     varchar2(50) not null,
   date_of_birth date not null,
   email         varchar2(100) not null unique,
   password      varchar2(256) default 'password' not null,
   class_id      number null,
   constraint fk_student_class foreign key ( class_id )
      references class ( class_id )
);